---
client_name:
  long: "Potos Linux Client"
  short: "potos"
disk_encryption:
  enable: false
  init_password: "install"
specs:
  url: "https://github.com/hobasp2/"
  repo: "ansible-specs-potos-hobasp2"
  branch: "main"
  ssh_key: ""  # eg. ssh_key: "potos_specs_key" for `potos_specs_key` in this config directory
  ansible-vault-key-file: ""  # same as ssh_key, but for the file with the ansible-vault key
initial_hostname: "potos-test"
initial_user:
  username: "holgerb"
  password: "Tuxtux1!"
environment: "develop"
first_boot_ansible:
  runtype: "setup"
full_unattended_install: false
os: "jammy"
output:
  version: "%Y%m%d"
  iso_filename: "potos-installer.iso"
